[project]
name = "franka-chess-tournament"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pybullet>=3.2.7",
    "scipy>=1.16.2",
]
